
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.51.75:3306/test?useUnicode=true&characterEncoding=utf8
      password: root
      username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 192.168.51.75
    port: 6379
    database: 1
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
      force: true
my:
    name: after
    age: 23
    msg: Test is ok
    number: ${random.int}
    uuid: ${random.uuid}
    max: ${random.int(10)}
    value: ${random.value}
    greeting: Hi,I'm ${my.name}
logging:
  file: /mnt/spring-boot/log.log
server:
  servlet:
    context-path: /helloboot
#debug: true
