mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  config-location: classpath:mybatisConfig.xml
spring:
  thymeleaf:
    cache: false
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
      force: true
my:
    name: aftermysql
    age: 23
    msg: Test is ok
    number: ${random.int}
    uuid: ${random.uuid}
    max: ${random.int(10)}
    value: ${random.value}
    greeting: Hi,I'm ${my.name}
logging:
  file:
    name: /mnt/spring-boot/root.log
#server:
#  servlet:
#    context-path: /helloboot
#debug: true
# 线程池配置
thread:
  pool:
    # 核心线程数
    core-pool-size: 8
    # 最大线程数
    max-pool-size: 16
    # 工作队列容量
    queue-capacity: 100
    # 线程池维护线程所允许的空闲时间
    keep-alive-seconds: 300