mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
spring:
  thymeleaf:
    cache: false
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
      password: 123456
      username: root
      type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
      force: true
my:
    name: after
    age: 23
    msg: Test is ok
    number: ${random.int}
    uuid: ${random.uuid}
    max: ${random.int(10)}
    value: ${random.value}
    greeting: Hi,I'm ${my.name}
logging:
  file: /mnt/spring-boot/log.log
#server:
#  servlet:
#    context-path: /helloboot
#debug: true
