## Memcache ≈‰÷√ ##
memcache:
  host: 119.3.49.192
  port: 12000
  servers: 119.3.49.192:12000
  failover: true
  initConn: 100
  minConn: 20
  maxConn: 1000
  maintSleep: 50
  nagel: false
  socketTO: 3000
  aliveCheck: true
