server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: consumer-service
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null
dubbo:
  application:
    name: consumer-service
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
    check: false
    group: ${spring.profiles.active}
  consumer:
    check: false
  scan:
    base-packages: com.example.demo.service
  protocol:
    name: dubbo
    port: -1