server:
  port: 8081
spring:
  application:
    name: consumer-service
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null
dubbo:
  application:
    name: consumer-service
  registry:
    address: nacos://172.26.96.1:8848
    username: nacos
    password: nacos
    check: true
    group: dubbo_group
  consumer:
    check: false
  scan:
    base-packages: com.example.demo.service
  protocol:
    name: dubbo
    port: -1