server:
  port: 8000
spring:
  profiles:
    active: dev
  application:
    name: provider-service
  main:
    allow-bean-definition-overriding: true
dubbo:
  application:
    name: provider-service
    qos-enable: false
    qos-accept-foreign-ip: false
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos

    
    check: false
    group: ${spring.profiles.active}
  provider:
    group: ${spring.profiles.active}
    version: 0.2.0
  scan:
    base-packages: com.example.demo.service.impl
  protocol:
    name: dubbo
    port: 20800
