server:
  port: 8000
spring:
  application:
    name: provider-service
  main:
    allow-bean-definition-overriding: true
dubbo:
  application:
    name: provider-service
    logger: log4j2
    qos-enable: false
    qos-accept-foreign-ip: false
  registry:
    address: nacos://172.24.230.37:8848
    username: nacos
    password: nacos
  scan:
    base-packages: com.example.demo.service.impl
  protocol:
    name: dubbo
    port: 20800
