spring:
  profiles: dev
  freemarker:
    prefer-file-system-access: false
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.1.37:8761/eureka/
#    register-with-eureka: false
    fetch-registry: false